import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaTimes, FaCheckCircle, FaBitcoin } from 'react-icons/fa';
import { SiEthereum } from 'react-icons/si';

export interface DCAParameters {
  amount: number;
  token: string;
  frequency: 'daily' | 'weekly' | 'monthly';
  duration: number; // in months
  startDay?: string; // e.g., "Monday" or "1st"
}

interface DCAConfirmationModalProps {
  isOpen: boolean;
  parameters: DCAParameters | null;
  onClose: () => void;
  onApprove: (params: DCAParameters) => void;
}

const tokenIcons: Record<string, React.ReactNode> = {
  'BTC': <FaBitcoin className="text-orange-400" />,
  'ETH': <SiEthereum className="text-blue-400" />,
  'SOL': <span className="text-purple-400">◎</span>,
};

const frequencyLabels: Record<string, string> = {
  'daily': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
};

export const DCAConfirmationModal: React.FC<DCAConfirmationModalProps> = ({
  isOpen,
  parameters,
  onClose,
  onApprove,
}) => {
  if (!parameters) return null;

  const totalInvestment = parameters.amount * parameters.duration * (
    parameters.frequency === 'daily' ? 30 :
    parameters.frequency === 'weekly' ? 4 :
    1
  );

  const handleApprove = () => {
    onApprove(parameters);
    onClose();
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
            className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-md z-50"
          >
            <div className="bg-gradient-to-br from-gray-900/95 to-gray-800/95 backdrop-blur-xl rounded-2xl shadow-2xl border border-white/10 overflow-hidden">
              {/* Header */}
              <div className="bg-gradient-to-r from-emerald-500/20 to-blue-500/20 px-6 py-4 border-b border-white/10">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className="w-10 h-10 bg-emerald-400/20 rounded-full flex items-center justify-center">
                      <FaCheckCircle className="text-emerald-400 text-xl" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold text-white">Confirm DCA Plan</h3>
                      <p className="text-xs text-gray-400">Review your investment details</p>
                    </div>
                  </div>
                  <button
                    onClick={onClose}
                    className="text-gray-400 hover:text-white transition-colors"
                  >
                    <FaTimes className="text-xl" />
                  </button>
                </div>
              </div>

              {/* Body */}
              <div className="p-6 space-y-6">
                {/* AI Agent Generated Badge */}
                <div className="flex items-center justify-center">
                  <div className="inline-flex items-center space-x-2 px-3 py-1.5 bg-blue-500/10 border border-blue-500/20 rounded-full">
                    <span className="w-2 h-2 bg-blue-400 rounded-full animate-pulse"></span>
                    <span className="text-xs text-blue-300 font-medium">Generated by IGL AI Agent</span>
                  </div>
                </div>

                {/* Investment Details Card */}
                <div className="bg-white/5 backdrop-blur-sm rounded-xl border border-white/10 overflow-hidden">
                  {/* Amount Row */}
                  <div className="flex items-center justify-between p-4 border-b border-white/10">
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Investment Amount</p>
                      <p className="text-2xl font-bold text-white">${parameters.amount}</p>
                    </div>
                    <div className="text-4xl">
                      {tokenIcons[parameters.token] || '💰'}
                    </div>
                  </div>

                  {/* Token Row */}
                  <div className="flex items-center justify-between p-4 border-b border-white/10">
                    <p className="text-sm text-gray-400">Token</p>
                    <div className="flex items-center space-x-2">
                      <span className="text-lg font-semibold text-white">{parameters.token}</span>
                      <span className="text-xs text-gray-500">
                        {parameters.token === 'BTC' ? 'Bitcoin' :
                         parameters.token === 'ETH' ? 'Ethereum' :
                         parameters.token === 'SOL' ? 'Solana' : ''}
                      </span>
                    </div>
                  </div>

                  {/* Frequency Row */}
                  <div className="flex items-center justify-between p-4 border-b border-white/10">
                    <p className="text-sm text-gray-400">Frequency</p>
                    <div className="flex items-center space-x-2">
                      <span className="text-sm font-semibold text-white">
                        {frequencyLabels[parameters.frequency]}
                      </span>
                      {parameters.startDay && (
                        <span className="text-xs text-emerald-400">
                          ({parameters.startDay})
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Duration Row */}
                  <div className="flex items-center justify-between p-4">
                    <p className="text-sm text-gray-400">Duration</p>
                    <p className="text-sm font-semibold text-white">
                      {parameters.duration} month{parameters.duration > 1 ? 's' : ''}
                    </p>
                  </div>
                </div>

                {/* Summary Box */}
                <div className="bg-gradient-to-r from-emerald-500/10 to-blue-500/10 rounded-xl p-4 border border-emerald-500/20">
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-xs text-gray-300">Total Investment</p>
                    <p className="text-xs text-emerald-400">
                      {parameters.frequency === 'daily' ? `${parameters.duration * 30} days` :
                       parameters.frequency === 'weekly' ? `${parameters.duration * 4} weeks` :
                       `${parameters.duration} months`}
                    </p>
                  </div>
                  <div className="flex items-center justify-between">
                    <p className="text-2xl font-bold text-white">${totalInvestment.toLocaleString()}</p>
                    <p className="text-xs text-gray-400">
                      {parameters.frequency === 'daily' ? `$${parameters.amount} × ${parameters.duration * 30}` :
                       parameters.frequency === 'weekly' ? `$${parameters.amount} × ${parameters.duration * 4}` :
                       `$${parameters.amount} × ${parameters.duration}`}
                    </p>
                  </div>
                </div>

                {/* Risk Warning */}
                <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">
                  <p className="text-xs text-yellow-200/80 leading-relaxed">
                    ⚠️ <span className="font-semibold">Risk Disclaimer:</span> Cryptocurrency investments are highly volatile. Only invest what you can afford to lose. Past performance does not guarantee future results.
                  </p>
                </div>
              </div>

              {/* Footer - Action Buttons */}
              <div className="px-6 pb-6 flex space-x-3">
                <button
                  onClick={onClose}
                  className="flex-1 px-6 py-3 bg-white/5 hover:bg-white/10 text-white rounded-xl border border-white/10 transition-all duration-200 font-medium"
                >
                  Cancel
                </button>
                <button
                  onClick={handleApprove}
                  className="flex-1 px-6 py-3 bg-gradient-to-r from-emerald-400 to-blue-400 hover:from-emerald-500 hover:to-blue-500 text-white rounded-xl font-semibold shadow-lg shadow-emerald-500/20 transition-all duration-200 flex items-center justify-center space-x-2"
                >
                  <FaCheckCircle />
                  <span>Approve Plan</span>
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};
